language: python
python:
  - 2.7
  - 3.6
script:
  - pip install nose coverage coveralls
  - nosetests ./ ./docs
    --with-coverage --cover-package=rail --cover-html --cover-erase
    --with-doctest --doctest-extension=md --doctest-options=+ELLIPSIS,+IGNORE_EXCEPTION_DETAIL
after_success:
  - coveralls
