language: python
python:
  - 2.7
  - 3.6
script:
  - pip install nose mock coverage
  - nosetests ./ ./docs
    --with-coverage --cover-package=rail --cover-html --cover-erase
    --with-doctest --doctest-extension=md --doctest-options=+ELLIPSIS,+IGNORE_EXCEPTION_DETAIL
  - pip install pycodestyle
  - pycodestyle ./ --show-source --select=E,W
after_success:
  - pip install coveralls
  - coveralls
